In [9]:
import numpy as np

def cargar_datos(ruta_archivo):
  datos = np.genfromtxt(ruta_archivo, delimiter=',', skip_header=1)
  return datos

if __name__ == "__main__":
    ruta_archivo = '/content/drive/MyDrive/BOOTCAMP MITIC 2024/CIENCIA DE DATOS/data/retail_sales_dataset.csv'
    datos = cargar_datos(ruta_archivo)
    print(datos)


[[   1.   nan   nan ...    3.   50.  150.]
 [   2.   nan   nan ...    2.  500. 1000.]
 [   3.   nan   nan ...    1.   30.   30.]
 ...
 [ 998.   nan   nan ...    4.   25.  100.]
 [ 999.   nan   nan ...    3.   50.  150.]
 [1000.   nan   nan ...    4.   30.  120.]]


In [10]:
arr = datos[:, np.isfinite(datos).all(axis=0)]
print(arr)

[[   1.   34.    3.   50.  150.]
 [   2.   26.    2.  500. 1000.]
 [   3.   50.    1.   30.   30.]
 ...
 [ 998.   23.    4.   25.  100.]
 [ 999.   36.    3.   50.  150.]
 [1000.   47.    4.   30.  120.]]


In [11]:
arr = datos[:, np.isfinite(datos).all(axis=0)]
print(arr)

[[   1.   34.    3.   50.  150.]
 [   2.   26.    2.  500. 1000.]
 [   3.   50.    1.   30.   30.]
 ...
 [ 998.   23.    4.   25.  100.]
 [ 999.   36.    3.   50.  150.]
 [1000.   47.    4.   30.  120.]]


In [12]:
print(arr.size)

5000
